version: "3.8"

networks:
  nginx_net:
    driver: bridge

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net

  webcolorblue:
    image: fabricioveronez/web-color:blue
    networks:
      - nginx_net

  webcolorgreen:
    image: fabricioveronez/web-color:green

    networks:
      - nginx_net

  conversaotemperatura01:
    image: fabricioveronez/conversao-temperatura:v1

    networks:
      - nginx_net
  conversaotemperatura02:
    image: fabricioveronez/conversao-temperatura:v1
    networks:
      - nginx_net
  conversaotemperatura03:
    image: fabricioveronez/conversao-temperatura:v1
    networks:
      - nginx_net
